name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: Build APK using Cordova
        run: |
          npm install -g cordova

          cordova platform remove android 2>/dev/null || true
          cordova platform add android@13.0.0 --skip-link
          cordova build android --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ColorMixer-APK
          path: '**/app-debug.apk'
